# Reference

##<들어가기 전에> 파이썬 오픈 라이브러리
- NumPy(넘파이) https://numpy.org
  - Numerical Python, 파이썬 산술 계산을 위한 배열 기반의 라이브러리
- Pandas(판다스) https://pandas.pydata.org
  - 구조화된 데이터나 표 형식의 데이터를 쉽고 표현적으로 다루도록 설계된 라이브러리
  - DataFrame, Series 등의 자료구조 제공
- SciPy(사이파이) https://scipy.org/scipylib
  - 과학계산 관련 패키지 모음
- Matplotlib(맷플롯립) https://matplotlib.org
  - 그래프나 2차원 데이터 시각화를 위한 라이브러리
- IPython(아이파이썬) https://github.com/ipython/ipyparallel
- Jupyter(주피너) https://jupyter.org
  - 테스트하고 디버깅이 가능하도록 하는 라이브러리
- sckit-learn(사이킷런) https://scikit-learn.org/stable
  - 범용 머신러닝 라이브러리
- statsmodels(스태츠모델) https://www.statsmodels.org/stable/index.html
  - 통계분석 패키지 모음
- TensorFlow(텐서플로) https://www.tensorflow.org/?hl=ko
  - 딥러닝 관련 패키지 모음 (페이스북 개발)
- Keras(케라스) https://keras.io/
  - Python Deep Learning API (딥러닝 관련 패키지)
  - 활용예제 : https://blog.naver.com/agapeuni/222466487025

##Numpy

Numpy는 Python에서 과학 연산을 위한 가장 기본적인 패키지 중 하나입니다. Numpy는 'Numeric Python'의 약자이며, 대규모 다차원 배열과 행렬 연산에 필요한 다양한 함수와 메소드를 제공합니다. Numpy는 데이터 분석, 데이터 처리, 선형대수, 머신러닝 등 다양한 분야에서 널리 사용되고 있습니다.

###Numpy의 설치
- Numpy를 사용하기 위해서는 먼저 Numpy 패키지를 설칳야 합니다. 아래의 명령어를 사용하여 Numpy를 설치할 수 있습니다.
```python
pip install numpy
```

###Numpy 활용

In [4]:
import numpy as np

Numpy에서 가장 기본적인 데이터 구조는 배열입니다. Numpy배열은 동일한 타입의 데이터를 담는 다차원 배열입니다. Numpy배열은 ```ndarray``` 클래스를 사용하여 생성할 수 있습니다.

In [7]:
nd1 = np.array([1,2,3])
print(nd1)
print(type(nd1))

[1 2 3]
<class 'numpy.ndarray'>


Numpy 배열은 다른 배열 또는 스칼라와의 연산을 지원합니다. **Numpy 배열의 연산은 배열의 ```원소별(element-wise)```로 이루어집니다.**

In [9]:
nd1 + nd1, nd1 - nd1, nd1 * nd1, nd1 / nd1

(array([2, 4, 6]), array([0, 0, 0]), array([1, 4, 9]), array([1., 1., 1.]))

In [10]:
nd1 * 10

array([10, 20, 30])

In [11]:
nd1.shap        # 배열의 형태를 알려준다.

(3,)

In [13]:
nd1.ndim        # 배열의 차원을 알려준다.

1

In [12]:
nd1.dtype       # ndarray에 포함된 데이터의 자료형을 알려준다.

dtype('int64')

In [15]:
# nd1 = [1,2,3] + (3 => [3,3,3])
nd1 + 3

array([4, 5, 6])

---
nd2 = np.array([[1,2,3],[4,5,6]])

In [17]:
nd2 = np.array([[1,2,3],[4,5,6]])
print(nd2)
print(nd2.shape)
print(nd2.ndim)
print(nd2.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
int64


---
(nd2 + 3 ) = (nd2 + [3,3,3])

In [18]:
nd2 + 3

array([[4, 5, 6],
       [7, 8, 9]])

In [23]:
nd2 + [3,3,3]

array([[4, 5, 6],
       [7, 8, 9]])

---
(nd2 + [1,2,3]) = (nd2 + [[1,2,3],[1,2,3]])

In [19]:
nd2 + [1,2,3]

array([[2, 4, 6],
       [5, 7, 9]])

In [22]:
nd2 + [[1,2,3],[1,2,3]]

array([[2, 4, 6],
       [5, 7, 9]])

In [24]:
nd2 + [1,2]

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [26]:
nd3 = np.arange(5)
nd3

array([0, 1, 2, 3, 4])

In [28]:
nd4 = np.arange(12).reshape(3,4)
nd4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
nd1 = np.arange(3)
nd2 = np.arange(3).reshape(3,1)
print('nd1 : ', nd1)
print('nd2 : ', nd2)
nd3 = nd1 + nd2
print(nd3)

print(nd1.shape, nd2.shape, nd3.shape)

nd1 :  [0 1 2]
nd2 :  [[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]
(3,) (3, 1) (3, 3)


In [35]:
nd1 = np.arange(12).reshape(4, 3)
nd1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [36]:
nd1.sum()

66

In [39]:
nd1.shape

(4, 3)

In [37]:
nd1.sum(0)

array([18, 22, 26])

In [38]:
nd1.sum(1)

array([ 3, 12, 21, 30])

In [40]:
nd1.mean(1)

array([ 1.,  4.,  7., 10.])

In [44]:
nd1 = np.arange(24).reshape(2,4,3)
print(nd1)
print(nd1.shape)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
(2, 4, 3)


In [51]:
# ↓
# (2, 4, 3)
print(nd1.mean(0))
print(nd1.mean(0).shape)

[[ 6.  7.  8.]
 [ 9. 10. 11.]
 [12. 13. 14.]
 [15. 16. 17.]]
(4, 3)


In [54]:
#    ↓
# (2, 4, 3)
print(nd1.mean(1))
print(nd1.mean(1).shape)

[[ 4.5  5.5  6.5]
 [16.5 17.5 18.5]]
(2, 3)


In [53]:
#       ↓
# (2, 4, 3)
print(nd1.mean(2))
print(nd1.mean(2).shape)

[[ 1.  4.  7. 10.]
 [13. 16. 19. 22.]]
(2, 4)


In [57]:
# 이거 잘 이해 안되네...
print(nd1.mean((0,1)))
print(nd1.mean((0,1)).shape)

[10.5 11.5 12.5]
(3,)


In [60]:
print(np.zeros((2,3)))
print(np.ones((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [65]:
nd1 = np.ones((2,3))
nd2 = nd1               # 깊은 복사 (주소값 복사)

In [66]:
nd2[0,0] = 100
print(nd2)
print(nd1)

[[100.   1.   1.]
 [  1.   1.   1.]]
[[100.   1.   1.]
 [  1.   1.   1.]]


In [67]:
nd3 = nd1.copy()       # 얕은 복사 (값만 복사)
nd3[0,0] = 200
print(nd3)
print(nd1)

[[200.   1.   1.]
 [  1.   1.   1.]]
[[100.   1.   1.]
 [  1.   1.   1.]]


In [68]:
nd1 = np.arange(12).reshape(3,4)
nd1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [71]:
nd2 = np.zeros_like(nd1)    # shape은 동일하게 초기값은 0으로 생성
nd2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

####mean - axis

In [72]:
nd1 = np.arange(24).reshape(2,3,4)
nd1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [74]:
print('nd1.mean(0) : ', nd1.mean(0))
print('nd1.mean(1) : ', nd1.mean(1))
print('nd1.mean(2) : ', nd1.mean(2))

nd1.mean(0) :  [[ 6.  7.  8.  9.]
 [10. 11. 12. 13.]
 [14. 15. 16. 17.]]
nd1.mean(1) :  [[ 4.  5.  6.  7.]
 [16. 17. 18. 19.]]
nd1.mean(2) :  [[ 1.5  5.5  9.5]
 [13.5 17.5 21.5]]


In [75]:
nd1 = np.array([1,2,3], dtype=np.int32)
nd1

array([1, 2, 3], dtype=int32)

In [76]:
nd1 = np.array([1,2,3], dtype=np.float32)
nd1

array([1., 2., 3.], dtype=float32)

In [78]:
nd1 = np.array([4,5,6])
nd2 = np.array([1,2,3])
print(nd1.dtype, nd2.dtype)

int64 int64


In [79]:
nd3 =  nd1 / nd2
print(nd3.dtype)

float64


In [81]:
nd1 = np.arange(24)
nd1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [83]:
nd1[5:12]

array([ 5,  6,  7,  8,  9, 10, 11])

In [84]:
nd1[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [85]:
nd1[5:12] = 100
nd1

array([  0,   1,   2,   3,   4, 100, 100, 100, 100, 100, 100, 100,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [86]:
nd1 = np.arange(36).reshape(3,3,4)
nd1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [87]:
nd1[:2]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [92]:
# 배열의 차수별로 ',' 기준으로 슬라이싱 설정
nd1[:2, 1:, :]

array([[[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [95]:
# 평균이 0이고, 표준편차가 1인 정규분포를 따르는 난수를 가지는 배열을 생성합니다.
nd1 = np.random.rand(8, 4)
nd1

array([[0.93828053, 0.49788215, 0.7109625 , 0.2538202 ],
       [0.6115028 , 0.86635553, 0.53687779, 0.27681371],
       [0.65513317, 0.27853066, 0.43393647, 0.36090118],
       [0.07548081, 0.00101207, 0.25577793, 0.51848555],
       [0.98398431, 0.59021252, 0.20935578, 0.32726197],
       [0.22930082, 0.96329267, 0.05434464, 0.50615433],
       [0.43548006, 0.38465785, 0.24279869, 0.44909459],
       [0.73195114, 0.98788241, 0.78827856, 0.29146908]])

In [96]:
nd2 = np.array(['a', 'b', 'c', 'a', 'b', 'a', 'b', 'c'])
nd2

array(['a', 'b', 'c', 'a', 'b', 'a', 'b', 'c'], dtype='<U1')

####boolean 색인

In [99]:
nd1[nd2=='a']

array([[0.93828053, 0.49788215, 0.7109625 , 0.2538202 ],
       [0.07548081, 0.00101207, 0.25577793, 0.51848555],
       [0.22930082, 0.96329267, 0.05434464, 0.50615433]])

In [98]:
print(nd2=='a')

[ True False False  True False  True False False]


In [101]:
nd1[[True, False, False, True, False, True, False, False]]

array([[0.93828053, 0.49788215, 0.7109625 , 0.2538202 ],
       [0.07548081, 0.00101207, 0.25577793, 0.51848555],
       [0.22930082, 0.96329267, 0.05434464, 0.50615433]])

In [103]:
nd1[nd1 > 0.5]

array([0.93828053, 0.7109625 , 0.6115028 , 0.86635553, 0.53687779,
       0.65513317, 0.51848555, 0.98398431, 0.59021252, 0.96329267,
       0.50615433, 0.73195114, 0.98788241, 0.78827856])

In [104]:
nd1 > 0.5

array([[ True, False,  True, False],
       [ True,  True,  True, False],
       [ True, False, False, False],
       [False, False, False,  True],
       [ True,  True, False, False],
       [False,  True, False,  True],
       [False, False, False, False],
       [ True,  True,  True, False]])

In [105]:
nd1[nd1 >= 0.5] = 1
nd1[nd1 < 0.5] = 0
nd1

array([[1., 0., 1., 0.],
       [1., 1., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 1., 0., 0.],
       [0., 1., 0., 1.],
       [0., 0., 0., 0.],
       [1., 1., 1., 0.]])

In [108]:
print('nd1 >= 0.5 : \n', nd1 >= 0.5)
print('nd1 < 0.5 : \n', nd1 < 0.5)

nd1 >= 0.5 : 
 [[ True False  True False]
 [ True  True  True False]
 [ True False False False]
 [False False False  True]
 [ True  True False False]
 [False  True False  True]
 [False False False False]
 [ True  True  True False]]
nd1 < 0.5 : 
 [[False  True False  True]
 [False False False  True]
 [False  True  True  True]
 [ True  True  True False]
 [False False  True  True]
 [ True False  True False]
 [ True  True  True  True]
 [False False False  True]]


In [110]:
# 평균이 0이고, 표준편차가 1인 정규분포를 따르는 난수를 가지는 배열을 생성합니다.
nd1 = np.random.rand(8, 4)
nd1

array([[0.44108846, 0.03879664, 0.88610482, 0.22780557],
       [0.79405442, 0.82129827, 0.34441384, 0.74138135],
       [0.22568498, 0.49259005, 0.30575607, 0.08404033],
       [0.99438417, 0.51920187, 0.92156232, 0.12179087],
       [0.83627541, 0.53129223, 0.5820373 , 0.58529528],
       [0.40043083, 0.43291879, 0.68494113, 0.83924974],
       [0.06659135, 0.28675908, 0.53449057, 0.7299914 ],
       [0.15321934, 0.44796246, 0.84045154, 0.26675201]])

In [117]:
# 펜시 색인???
# [[1,3],[3,1],[5,0],[6,3]]
nd1[[1,3,5,6],[2,1,0,3]]

array([0.34441384, 0.51920187, 0.40043083, 0.7299914 ])

####transpose()
- ndarray의 축을 바꿔준다.

In [118]:
nd1.transpose()

array([[0.44108846, 0.79405442, 0.22568498, 0.99438417, 0.83627541,
        0.40043083, 0.06659135, 0.15321934],
       [0.03879664, 0.82129827, 0.49259005, 0.51920187, 0.53129223,
        0.43291879, 0.28675908, 0.44796246],
       [0.88610482, 0.34441384, 0.30575607, 0.92156232, 0.5820373 ,
        0.68494113, 0.53449057, 0.84045154],
       [0.22780557, 0.74138135, 0.08404033, 0.12179087, 0.58529528,
        0.83924974, 0.7299914 , 0.26675201]])

In [119]:
nd1 = np.arange(24).reshape(2,3,4)
nd1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [123]:
# (1 <=> 0번) 축을 변경
# (2,3,4) => (3,2,4)
nd1_t = nd1.transpose((1,0,2))
print(nd1_t)
print(nd1_t.shape)

[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
(3, 2, 4)


####np.exp

In [124]:
np.exp(nd1)

array([[[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
        [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
        [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]],

       [[1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06],
        [8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08],
        [4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09]]])

####np.sqrt

In [125]:
np.sqrt(nd1)

array([[[0.        , 1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974, 2.64575131],
        [2.82842712, 3.        , 3.16227766, 3.31662479]],

       [[3.46410162, 3.60555128, 3.74165739, 3.87298335],
        [4.        , 4.12310563, 4.24264069, 4.35889894],
        [4.47213595, 4.58257569, 4.69041576, 4.79583152]]])

####np.where

In [128]:
# nd1[nd1 > 12] = 1
# nd1[nd1 <= 12] = 0
nd2 = np.where(nd1 > 12, 1, 0)
nd2

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [132]:
nd1 = np.arange(24).reshape(2,3,4)
nd1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [137]:
# nd1 >= 15 면 1, 아니면 원래 값(nd1)
nd2 = np.where(nd1 >= 15, 1, nd1)
nd2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14,  1],
        [ 1,  1,  1,  1],
        [ 1,  1,  1,  1]]])

In [140]:
nd2 = np.where(nd1 > 10, 1, np.where(nd1 < 5, 0, nd1))
nd2

array([[[ 0,  0,  0,  0],
        [ 0,  5,  6,  7],
        [ 8,  9, 10,  1]],

       [[ 1,  1,  1,  1],
        [ 1,  1,  1,  1],
        [ 1,  1,  1,  1]]])

####dot - matrix 곱

In [143]:
nd1 = np.arange(4).reshape(2,2)
nd1_t = nd1.transpose()
print(nd1)
print(nd1_t)
np.dot(nd1, nd1_t)


[[0 1]
 [2 3]]
[[0 2]
 [1 3]]


array([[ 1,  3],
       [ 3, 13]])

###Numpy로 유클리드 구현

In [144]:
# 구글 드라이브 마운트
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [145]:
# 나의 루트 경로 설정
rootdir = '/content/drive/MyDrive/Colab Notebooks/빅데이터분석과정'

In [155]:
data = np.loadtxt(rootdir + '/test.csv', delimiter=',', skiprows=1)
data

array([[4., 5., 6.],
       [7., 8., 9.]])

In [247]:
# skiprows 는 시작 몇라인을 skip할지를 설정하는 값
data = np.loadtxt(rootdir + '/diabetes.csv', delimiter=',', skiprows=1)
data

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [248]:
data.shape

(768, 9)

In [158]:
print(type(data))

<class 'numpy.ndarray'>



####구현 : dzP

In [186]:
# 배열데이터 유클리드 계산함수 구현
def dzp_euclidean_distances(data):
    distances = []
    lst_min = ['', '', -1]
    for i in range(len(data)):
        for j in range(i+1, len(data)):
            distances.append([data[i], data[j],euclidean_distance(data[i, :8], data[j, :8])])

            if (lst_min[2] == -1 or lst_min[2] > distances[-1][2]):
              lst_min = distances[-1]
    return lst_min

In [238]:
from scipy.spatial import distance
from math import dist

# 유클리드 거리계산 함수구현
def euclidean_distance(x, y):
    # Numpy 사용
    #return np.sqrt(np.sum((x - y) ** 2))
    # return np.sqrt(np.sum(np.square(x - y)))
    # return np.sqrt(np.dot((x-y).T, (x-y)))
    return np.linalg.norm(x - y)

    # scipy 사용
    # return distance.euclidean(x, y)

    # math 사용
    #return dist(x,y)

In [243]:
# 배열데이터 유클리드 계산함수 구현
def dzp_euclidean_distances(data):
    lst_min = ['', '', np.inf]
    for i in range(data.shape[0]):
        for j in range(i+1, data.shape[0]):
            distances = euclidean_distance(data[i, :8], data[j, :8])
            if (lst_min[2] > distances): lst_min = [data[i], data[j], distances]
    return lst_min

In [251]:
# 끝 문자 0, 1로 구분!
# 원본을 변경안하고, 복사본을 생성하려고, np.array()를 사용
nd_0 = np.array(data[data[:,8] == 0])
nd_1 = np.array(data[data[:,8] == 1])
print(nd_0.shape, nd_1.shape)
print(type(nd_0), type(nd_1))

(500, 9) (268, 9)
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [245]:
nd_0_ed = dzp_euclidean_distances(nd_0)
nd_1_ed = dzp_euclidean_distances(nd_1)
print(nd_0_ed)
print(nd_1_ed)

[array([ 6.   , 91.   ,  0.   ,  0.   ,  0.   , 29.8  ,  0.501, 31.   ,
        0.   ]), array([ 4.  , 90.  ,  0.  ,  0.  ,  0.  , 28.  ,  0.61, 31.  ,  0.  ]), 2.872608744677911]
[array([  2.   , 134.   ,  70.   ,   0.   ,   0.   ,  28.9  ,   0.542,
        23.   ,   1.   ]), array([  4.   , 136.   ,  70.   ,   0.   ,   0.   ,  31.2  ,   1.182,
        22.   ,   1.   ]), 3.834005738128205]


In [246]:
print('[0 번]\r')
print(nd_0_ed[0], '\n', nd_0_ed[1], '\n', nd_0_ed[2])
print('[1 번]\r')
print(nd_1_ed[0], '\n', nd_1_ed[1], '\n', nd_1_ed[2])

[0 번]
[ 6.    91.     0.     0.     0.    29.8    0.501 31.     0.   ] 
 [ 4.   90.    0.    0.    0.   28.    0.61 31.    0.  ] 
 2.872608744677911
[1 번]
[  2.    134.     70.      0.      0.     28.9     0.542  23.      1.   ] 
 [  4.    136.     70.      0.      0.     31.2     1.182  22.      1.   ] 
 3.834005738128205


####구현  :Teacher

In [249]:
ones = np.array(data[data[:,8] == 1])
zeros = np.array(data[data[:,8] == 0])
print(ones.shape, zeros.shape)

(268, 9) (500, 9)


In [258]:
def closed_pts(nd1):
  closed_dist = np.inf      # np.inf => 무한
  closed_pts = None
  for x in range(nd1.shape[0]):
    for y in range(x+1, nd1.shape[0]):
      if x != y:
        dist = np.sqrt(np.sum((nd1[x]-nd1[y])**2))
        if closed_dist > dist:
          closed_dist = dist
          closed_pts = (x,y)
  return closed_pts         # 배열의 차원수를 반환 (x,y)

closed_pts_ones = closed_pts(ones)
closed_pts_zeros = closed_pts(zeros)
print('=======================================================')
print('closed_pts(ones) : ', closed_pts_ones)
print('closed_pts(zeros) : ', closed_pts_zeros)
print('=======================================================')
print('ones[closed_pts(ones),]\n', ones[closed_pts_ones,])
print('zeros[closed_pts(zeros),]\n', zeros[closed_pts_zeros,])
print('=======================================================')

closed_pts(ones) :  (172, 260)
closed_pts(zeros) :  (345, 423)
ones[closed_pts(ones),]
 [[  2.    134.     70.      0.      0.     28.9     0.542  23.      1.   ]
 [  4.    136.     70.      0.      0.     31.2     1.182  22.      1.   ]]
zeros[closed_pts(zeros),]
 [[ 6.    91.     0.     0.     0.    29.8    0.501 31.     0.   ]
 [ 4.    90.     0.     0.     0.    28.     0.61  31.     0.   ]]
